spits-job-manager-instance-aws:
  provider: aws-east-1-config
  login: ubuntu-linux-login
  flavor: t2.medium
  image_id: ami-0b7f01152e09cbfd2
  security_group: spits-inbound-security-group

spits-worker-instance-aws-g4dn.xlarge:
  provider: aws-east-1-config
  login: ubuntu-linux-login
  flavor: g4dn.xlarge
  image_id: ami-0a9cf8fb826016288
  security_group: spits-inbound-security-group

spits-worker-instance-aws-g4dn.12xlarge:
  provider: aws-east-1-config
  login: ubuntu-linux-login
  flavor: g4dn.12xlarge
  image_id: ami-0a9cf8fb826016288
  security_group: spits-inbound-security-group

spits-worker-instance-aws-t2.small:
  provider: aws-east-1-config
  login: ubuntu-linux-login
  flavor: t2.small
  image_id: ami-0b7f01152e09cbfd2
  security_group: spits-inbound-security-group

spits-worker-instance-aws-t2.medium:
  provider: aws-east-1-config
  login: ubuntu-linux-login
  flavor: t2.medium
  image_id: ami-0b7f01152e09cbfd2
  security_group: spits-inbound-security-group

spits-worker-instance-aws-p2.xlarge:
  provider: aws-east-1-config
  login: ubuntu-linux-login
  flavor: p2.xlarge
  image_id: ami-06b21faebf9f37df2
  security_group: spits-inbound-security-group

spits-worker-instance-aws-p2.8xlarge:
  provider: aws-east-1-config
  login: ubuntu-linux-login
  flavor: p2.8xlarge
  image_id: ami-06b21faebf9f37df2
  security_group: spits-inbound-security-group

spits-worker-instance-aws-p2.16xlarge:
  provider: aws-east-1-config
  login: ubuntu-linux-login
  flavor:  p2.16xlarge
  image_id: ami-06b21faebf9f37df2
  security_group: spits-inbound-security-group

spits-worker-instance-aws-p3.2xlarge:
  provider: aws-east-1-config
  login: ubuntu-linux-login
  flavor: p3.2xlarge
  image_id: ami-0af05ad75c968fc8a
  security_group: spits-inbound-security-group

spits-worker-instance-aws-p3.8xlarge:
  provider: aws-east-1-config
  login: ubuntu-linux-login
  flavor: p3.8xlarge
  image_id: ami-0af05ad75c968fc8a
  security_group: spits-inbound-security-group

spits-worker-instance-aws-g4ad.xlarge:
  provider: aws-east-1-config
  login: ubuntu-linux-login
  flavor: g4ad.xlarge
  image_id: ami-0224cadd07bfd9724
  security_group: spits-inbound-security-group
