clusters:
  spits-cluster:
    before_all:
    - setup-common
    - setup-efs

    nodes:
      spits-jobmanager:
        type: spits-job-manager-instance-aws
        count: 1
        setups:
        - setup-binaries-jobmanager
        - setup-spits-jobmanager
        - setup-spits-job-jobmanager

      spits-taskmanager:
        type: spits-worker-instance-aws-{{instance_type}}
        count: 1
        setups:
        - setup-binaries-taskmanager
        - setup-spits-taskmanager
        - setup-spits-job-taskmanager

    after:
    - setup-spits-start-bin

    after_all:
    - setup-spits-add-nodes
